services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jeongeoneya0831!
      MYSQL_DATABASE: reper
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: jeongeoneya0831!
    ports:
      - "13790:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL Îç∞Ïù¥ÌÑ∞ Ï†ÄÏû•
      - mysql_config:/etc/mysql/conf.d  # MySQL ÏÑ§Ï†ï ÌååÏùº Ï†ÄÏû•
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx15g
    ports:
      - "23159:9200"
    volumes:
      - elastic_data:/elasticsearch/data
      - elasticsearch_logs:/elasticsearch/logs:rw
    networks:
      - elastic_network

  app:
    image: reper-server
    container_name: reper-server
    build:
      context: ./reper
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://i12d109.p.ssafy.io:13790/reper?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: jeongeoneya0831!
      FIREBASE_JSON: /app/config/firebase.json  # Firebase JSON Í≤ΩÎ°ú ÏÑ§Ï†ï
    ports:
      - "48620:8080"
    depends_on:
      - mysql
    volumes:
      - app_logs:/app/logs
      - /absolute/path/to/firebase.json:/app/config/firebase.json  # üî• ÏïàÏ†ÑÌïú Í≤ΩÎ°úÎ°ú ÎßàÏö¥Ìä∏
    networks:
      - app-network
  
  pdf-server:
    image: pdf-server
    container_name: pdf-server
    build:
      context: ./pdf
      dockerfile: Dockerfile
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "20250:20250"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:
  app_logs:
  elastic_data:
  elasticsearch_logs:

networks:
  app-network:
  elastic_network:
    driver: bridge
