spring:
  server:
    port: 48620
  config:
    import: optional:application-secrets.yml
  datasource:
    url: jdbc:mysql://i12d109.p.ssafy.io:13790/reper?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: jeongeoneya0831!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update # (ê°œë°œí™˜ê²½) -> (ìš´ì˜ í™˜ê²½) validation/none
    datasource:
      initialization-mode: always
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    uris: http://i12d109.p.ssafy.io:23159  # (ë³´ì•ˆ ì ìš©ë ë• httpsë¡œ ë°”ê¾¸ê¸°)
    socket-timeout: 60s
    username: ""  # ë³´ì•ˆ ë¹„í™œì„±í™”ì—ì„  ë¹ˆ ê°’
    password: ""
    ssl:
      enabled: false
    repositories:
      enabled: false
#    username: elastic
#    password: ${ELASTIC_PASSWORD}
#    index:
#      auto-create-index: false
#      ca-certificate: classpath:docker/certs/ca.crt
#      key: classpath:certs/elasticsearch.key
#      certificate: classpath:certs/elasticsearch.crt

firebase:
  credential: ${FIREBASE_JSON}  # ğŸ”¥ í™˜ê²½ ë³€ìˆ˜ì—ì„œ Firebase JSONì„ ê°€ì ¸ì˜¤ê¸°

logging.level:
  org.hibernate.SQL: debug # (ê°œë°œ í™˜ê²½) SQL ë¡œê·¸ ì¶œë ¥
  org.hibernate.orm.jdbc.bind: trace # (ê°œë°œ í™˜ê²½) SQL ë°”ì¸ë”© ê°’ ì¶œë ¥

springdoc.override-with-generic-response: false

kakao:
  client_id: 11a435ceceba6f2724e9f7b1b9b69f5b
  redirect_uri: http://i12d109.p.ssafy.io:13790/api/auth/callback


